### PR TITLE
Tests for Player.java (w/o tests for location, direction and move)

### PR DESCRIPTION
**Pull request by 5niperspider**
## What does this PR do?

Adding Tests for the class: Player

### CODE REVIEW

**Comment by 5niperspider** [comment]
Don´t know why it still has an error on build. No problems in IDE

**Review by mrpaulblack — APPROVED** [review]
LGTM :+1: ; all unit tests work fine for me so CI maybe breaks because of cashing...

(I squashed the one fix commit)

**Comment by Vulpes-Nix** [comment]
There is a failed check? Is this resolved / have you talked to Paul about this?

Also when you check booleans you can just use assertTrue or assertFalse. 
Here's a list of other assert commands that might come in handy: http://junit.sourceforge.net/javadoc/org/junit/Assert.html

**Comment by mrpaulblack** [comment]
Closing in favor of #24.

**Pull request closed without merging**
